# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "ja"
reviews:
  profile: "chill"
  high_level_summary: true
  poem: false
  auto_review:
    enabled: true
    drafts: false
chat:
  auto_reply: true
